// <auto-generated />
using System;
using HRAppExample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRAppExample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230902192733_InitilazDatabase")]
    partial class InitilazDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRAppExample.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments", "HR");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = 4,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        });
                });

            modelBuilder.Entity("HRAppExample.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("DATE");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Gender")
                        .HasMaxLength(6)
                        .HasColumnType("VARCHAR(6)");

                    b.Property<byte>("HasHealthInsurance")
                        .HasColumnType("TINYINT");

                    b.Property<byte>("HasPensionPlan")
                        .HasColumnType("TINYINT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("DATE");

                    b.Property<string>("IdCard")
                        .HasMaxLength(12)
                        .HasColumnType("VARCHAR(12)");

                    b.Property<string>("ImageUser")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR(250)");

                    b.Property<byte>("IsActive")
                        .HasColumnType("TINYINT");

                    b.Property<string>("JobTtitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("VARCHAR(14)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("Decimal(12,2)");

                    b.Property<string>("Skills")
                        .HasColumnType("VARCHAR(250)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees", "HR");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            BirthDate = new DateTime(1997, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "Cole.Cochran@example.com",
                            FirstName = "Cochran",
                            Gender = "male",
                            HasHealthInsurance = (byte)1,
                            HasPensionPlan = (byte)0,
                            HireDate = new DateTime(2010, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCard = "2010-FI-1234",
                            ImageUser = "User.png",
                            IsActive = (byte)0,
                            JobTtitle = "Adminstrator",
                            LastName = "Cole",
                            NationalId = "12345678912345",
                            Salary = 21000.00m,
                            Skills = "ASP.NET, CSS, Oracle"
                        },
                        new
                        {
                            Id = 1002,
                            BirthDate = new DateTime(1994, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "Wolfe.Jaclyn@example.com",
                            FirstName = "Jaclyn",
                            Gender = "male",
                            HasHealthInsurance = (byte)1,
                            HasPensionPlan = (byte)0,
                            HireDate = new DateTime(2011, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCard = "2011-IT-4563",
                            ImageUser = "User.png",
                            IsActive = (byte)0,
                            JobTtitle = "Web Developer",
                            LastName = "Wolfe",
                            NationalId = "12345678998765",
                            Salary = 25000.00m,
                            Skills = "ASP.NET, SQL Server, Javascript, CSS, HTML"
                        },
                        new
                        {
                            Id = 1003,
                            BirthDate = new DateTime(1995, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "Jones.Warner@example.com",
                            FirstName = "Warner",
                            Gender = "male",
                            HasHealthInsurance = (byte)1,
                            HasPensionPlan = (byte)1,
                            HireDate = new DateTime(2012, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCard = "2012-HR-7896",
                            ImageUser = "User.png",
                            IsActive = (byte)0,
                            JobTtitle = "Markting",
                            LastName = "Jones",
                            NationalId = "12345678936985",
                            Salary = 23000.00m,
                            Skills = "HTML, Oracle, SQL Server"
                        });
                });

            modelBuilder.Entity("HRAppExample.Models.Employee", b =>
                {
                    b.HasOne("HRAppExample.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HRAppExample.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
